#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
mhpb &> /dev/null

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier     mod4
bspc config history_aware_focus  true
bspc config pointer_action1      move
bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner
bspc config merge_overlapping_monitors  true

bspc config normal_border_color '#0d1117'
bspc config active_border_color '#4c566a'
bspc config focused_border_color '#84a0c6'
bspc config presel_feedback_color '#84a0c6'

bspc rule -a Gimp desktop=^3 state=floating follow=on
#bspc rule -a mpv desktop=^6 follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a firefox desktop=^3 follow=on
bspc rule -a TelegramDesktop desktop=^9
bspc rule -a discord desktop=^9
bspc rule -a arandr state=floating
