hwdec=auto
save-position-on-quit
keep-open=no
cursor-autohide=999
sub-auto=fuzzy
blend-subtitles=yes
#border=no
stop-screensaver
osd-duration=4000
osd-font-size=30
watch-later-directory=~/.local/share/mpv/

# Show this after loading a new file. You can show text permanently instead by setting osd-msg1.
osd-playing-msg=${!playlist-count==1:[${playlist-pos-1}/${playlist-count}] }${media-title} ${?width:${width}x${height}} ${?current-tracks/video/image==no:${?percent-pos==0:${duration}}${!percent-pos==0:${time-pos} / ${duration} (${percent-pos}%)}}
osd-playing-msg-duration=7000
