#!/bin/sh

case "$1" in
	*.sh|*.bash*|*.zsh*|*.fish|*.conf*|*.md|*.vim*) batcat --color always "$1";;
	*.bmp|*.jpg|*.jpeg|*.png|*.xpm) mediainfo "$1";;
	*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.flac) mediainfo "$1";;
	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx) mediainfo "$1";;
	*) highlight --out-format ansi "$1" || batcat --color always "$1";;
esac
